### ISSUE TITLE
TLS endpoint

### ISSUE THREAD

**Issue by rorist** [Pecamo/orbital#27]
It would be nice to have an tls/ssl supported webpage, in particular to integrate the lamp control in an other website ;)

Either using an nxing/apache proxy or directly in the app with something like this I guess https://advancedweb.hu/how-to-use-lets-encrypt-with-node-js-and-express/

**Comment by BinaryBrain** [comment]
The server now handle SSL certificates and can serve HTTPS pages. Letsencrypt has been directly installed on the Rpi at FIXME so it's standalone.
